---建表---{{{1

set define off;


----------------ObjectDeleteScript----------------

--delete  from maxobjectcfg  where objectname='MOBILEVERSION';
--delete  from maxtablecfg  where TABLENAME='MOBILEVERSION';
--delete  from maxattributecfg  where OBJECTNAME='MOBILEVERSION';
--delete  from maxsysindexes where TBNAME= 'MOBILEVERSION';
--delete from maxsyskeys where IXNAME='MOBILEVERSION_NDX1';
--delete  from maxrelationship where PARENT= 'MOBILEVERSION';
--delete  from maxsequence where TBNAME= 'MOBILEVERSION';


----------------ObjectInsertScript----------------



----------------CreateObjectScript----------------

insert into maxobjectcfg ( OBJECTNAME, CLASSNAME, DESCRIPTION, EAUDITENABLED, EAUDITFILTER, ENTITYNAME, ESIGFILTER, EXTENDSOBJECT, IMPORTED, ISVIEW, PERSISTENT, SERVICENAME, SITEORGTYPE, USERDEFINED, CHANGED, MAINOBJECT, INTERNAL, MAXOBJECTID, TEXTDIRECTION) values ( 'MOBILEVERSION', 'psdi.mbo.custapp.CustomMboSet', '移动端版本维护', 0, null, 'MOBILEVERSION', null, null, 0, 0, 1, 'CUSTAPP', '系统', 1,'I', 0, 0, MAXOBJECTCFGSEQ.nextval, null);


----------------CreateTableScript----------------

insert into maxtablecfg ( TABLENAME, ADDROWSTAMP, EAUDITTBNAME, ISAUDITTABLE, RESTOREDATA, STORAGEPARTITION, TEXTSEARCHENABLED, LANGTABLENAME, LANGCOLUMNNAME, UNIQUECOLUMNNAME, ISLANGTABLE, MAXTABLEID, ALTIXNAME, TRIGROOT, CONTENTATTRIBUTE, STORAGETYPE, EXTTABLENAME) values ( 'MOBILEVERSION', 1, null, 0, 0, 'MAXDATA', 0, null, null, 'MOBILEVERSIONID', 0, MAXTABLECFGSEQ.nextval, null, 'MOBILEVERSION', null, 0, null);


----------------CreateAttributeScript----------------

insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'MOBILEVERSIONID', 'MOBILEVERSIONID', null, 1, 0, null, 'MOBILEVERSIONID', null, null, 0, 'MOBILEVERSION', 0, 0, 0, 19, 'BIGINT', 1, 1, 1, 1, '唯一ID', null, null, 0, '唯一ID', 1,'I', 'EXACT', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'DESCRIPTION', 'DESCRIPTION', null, 2, 0, null, 'DESCRIPTION', null, null, 0, 'MOBILEVERSION', 0, 1, 0, 50, 'ALN', 0, 0, 1, null, '描述', null, null, 0, '描述', 1,'I', 'NONE', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 1, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'DESCRIPTION_LONGDESCRIPTION', 'DESCRIPTION_LONGDESCRIPTION', null, 3, 0, null, null, null, null, 0, null, 0, 0, 0, 32000, 'LONGALN', 1, 0, 0, null, 'Description_longdescription', null, null, 0, 'Description_longdescription', 1,'I', 'TEXT', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'HASLD', 'HASLD', null, 4, 0, null, 'HASLD', '0', null, 0, 'MOBILEVERSION', 0, 0, 0, 1, 'YORN', 1, 1, 1, null, 'Hasld', null, null, 0, 'Hasld', 1,'I', 'NONE', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'VERSION', 'VERSION', null, 5, 0, 'com.wmc.app.mobilevers.FldMVVersion', 'VERSION', null, null, 0, 'MOBILEVERSION', 0, 0, 0, 30, 'ALN', 0, 0, 1, null, '版本号', null, null, 0, '版本号', 1,'I', 'WILDCARD', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 1, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'VERSION1', 'VERSION1', null, 6, 0, 'com.wmc.app.mobilevers.FldMVVersion', 'VERSION1', null, null, 0, 'MOBILEVERSION', 0, 0, 0, 12, 'INTEGER', 0, 0, 1, null, '模块版本号,该版本更新将会强制要求用户更新', null, null, 0, '模块版本号', 1,'I', 'EXACT', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'VERSION2', 'VERSION2', null, 7, 0, 'com.wmc.app.mobilevers.FldMVVersion', 'VERSION2', null, null, 0, 'MOBILEVERSION', 0, 0, 0, 12, 'INTEGER', 0, 0, 1, null, '重要更新版本号,该版本更新将会强制要求客户端更新', null, null, 0, '重要更新版本号', 1,'I', 'EXACT', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'VERSION3', 'VERSION3', null, 8, 0, 'com.wmc.app.mobilevers.FldMVVersion', 'VERSION3', null, null, 0, 'MOBILEVERSION', 0, 0, 0, 12, 'INTEGER', 0, 0, 1, null, '优化更新,UI更新,对本地数据库不做任何改动,无需用户强制更新', null, null, 0, '优化更新', 1,'I', 'EXACT', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'UPDATEDLOG', 'UPDATEDLOG', null, 9, 0, null, 'UPDATEDLOG', null, null, 0, 'MOBILEVERSION', 0, 0, 0, 500, 'ALN', 0, 0, 1, null, '更新日志', null, null, 0, '更新日志', 1,'I', 'WILDCARD', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 1, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'SYSTEMTYPE', 'SYSTEMTYPE', null, 10, 0, null, 'SYSTEMTYPE', null, 'MPSYSTEMTYPE', 0, 'MOBILEVERSION', 0, 0, 0, 30, 'ALN', 0, 0, 1, null, '系统类别,android/ios', null, null, 0, '系统类别', 1,'I', 'WILDCARD', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 1, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'VERSIONNUM', 'VERSIONNUM', null, 11, 0, null, 'VERSIONNUM', null, null, 0, 'MOBILEVERSION', 0, 0, 0, 19, 'BIGINT', 0, 0, 1, null, '版本号数字化编码,该字段最大的那个为最新的版本号', null, null, 0, '版本号数字化编码', 1,'I', 'EXACT', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'ENABLED', 'ENABLED', null, 12, 0, null, 'ENABLED', '0', null, 0, 'MOBILEVERSION', 0, 0, 0, 1, 'YORN', 0, 1, 1, null, '启用', null, null, 0, '启用', 1,'I', 'EXACT', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'CREATEDATE', 'CREATEDATE', null, 13, 0, null, 'CREATEDATE', null, null, 0, 'MOBILEVERSION', 0, 0, 0, 10, 'DATETIME', 0, 0, 1, null, '创建时间', null, null, 0, '创建时间', 1,'I', 'EXACT', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'MOBILEVERSION', 'URL', 'URL', null, 14, 0, null, 'URL', null, null, 0, 'MOBILEVERSION', 0, 0, 0, 300, 'ALN', 0, 0, 1, null, '下载地址', null, null, 0, '下载地址', 1,'I', 'WILDCARD', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 1, null, null, 0);


----------------CreateindexScript----------------

insert into maxsysindexes ( NAME, TBNAME, UNIQUERULE, CHANGED, CLUSTERRULE, STORAGEPARTITION, REQUIRED, TEXTSEARCH, MAXSYSINDEXESID) values ( 'MOBILEVERSION_NDX1', 'MOBILEVERSION', 'U','Y', 0, 'MAXDATA', 1, 0, MAXSYSINDEXESSEQ.nextval);


----------------CreateKeyScript----------------

insert into maxsyskeys ( IXNAME, COLNAME, COLSEQ, ORDERING, CHANGED, MAXSYSKEYSID) values ( 'MOBILEVERSION_NDX1', 'MOBILEVERSIONID', 1, 'A','Y', MAXSYSKEYSSEQ.nextval);


----------------CreateRelationScript----------------

insert into maxrelationship ( NAME, PARENT, CHILD, WHERECLAUSE, REMARKS, MAXRELATIONSHIPID, CARDINALITY, DBJOINREQUIRED) values ( 'DOCLINKS', 'MOBILEVERSION', 'DOCLINKS', '(ownertable=''MOBILEVERSION'' and ownerid=:MOBILEVERSIONID)', null, MAXRELATIONSHIPSEQ.nextval, null, 0);


----------------CreateSequenceScript----------------

insert into maxsequence ( TBNAME, NAME, MAXRESERVED, MAXVALUE, RANGE, SEQUENCENAME, MAXSEQUENCEID) values ( 'MOBILEVERSION', 'MOBILEVERSIONID', 1, null, null, 'MOBILEVERSIONIDSEQ', MAXSEQUENCESEQ.nextval);


----------------Update Maximo Sequence----------------

update maxsequence set maxreserved=(select max(MOBILEVERSIONID)+1 from MOBILEVERSION) where tbname='MOBILEVERSION' and name='MOBILEVERSIONID';


----------------CreateAutokeyScript----------------


---应用---{{{1
app:MOBILEVERS
DESCRIPTION:移动端版本维护
MAINTBNAME:MOBILEVERSION


insert into Sigoption ( APP, OPTIONNAME, DESCRIPTION, ESIGENABLED, VISIBLE, ALSOGRANTS, ALSOREVOKES, PREREQUISITE, SIGOPTIONID, LANGCODE, HASLD) values ( 'MOBILEVERS', 'ASSOCFOLD', '关联文件夹', 0, 1, null, null, null, SIGOPTIONSEQ.nextval, 'ZH', 0);
insert into Sigoption ( APP, OPTIONNAME, DESCRIPTION, ESIGENABLED, VISIBLE, ALSOGRANTS, ALSOREVOKES, PREREQUISITE, SIGOPTIONID, LANGCODE, HASLD) values ( 'MOBILEVERS', 'MANAGEFOLD', '管理文件夹', 0, 1, null, null, null, SIGOPTIONSEQ.nextval, 'ZH', 0);
insert into Sigoption ( APP, OPTIONNAME, DESCRIPTION, ESIGENABLED, VISIBLE, ALSOGRANTS, ALSOREVOKES, PREREQUISITE, SIGOPTIONID, LANGCODE, HASLD) values ( 'MOBILEVERS', 'MANAGELIB', '管理库', 0, 1, null, null, null, SIGOPTIONSEQ.nextval, 'ZH', 0);
insert into Maxmenu ( MENUTYPE, MODULEAPP, POSITION, SUBPOSITION, ELEMENTTYPE, KEYVALUE, HEADERDESCRIPTION, URL, VISIBLE, IMAGE, ACCESSKEY, TABDISPLAY, MAXMENUID) values ( 'APPMENU', 'MOBILEVERS', 17, 0, 'OPTION', 'MANAGELIB', null, null, 1, null, null, '主要', MAXMENUSEQ.nextval);
insert into Maxmenu ( MENUTYPE, MODULEAPP, POSITION, SUBPOSITION, ELEMENTTYPE, KEYVALUE, HEADERDESCRIPTION, URL, VISIBLE, IMAGE, ACCESSKEY, TABDISPLAY, MAXMENUID) values ( 'APPMENU', 'MOBILEVERS', 15, 0, 'OPTION', 'MANAGEFOLD', null, null, 1, null, null, '主要', MAXMENUSEQ.nextval);
insert into Maxmenu ( MENUTYPE, MODULEAPP, POSITION, SUBPOSITION, ELEMENTTYPE, KEYVALUE, HEADERDESCRIPTION, URL, VISIBLE, IMAGE, ACCESSKEY, TABDISPLAY, MAXMENUID) values ( 'APPMENU', 'MOBILEVERS', 16, 0, 'OPTION', 'ASSOCFOLD', null, null, 1, null, null, '主要', MAXMENUSEQ.nextval);



----------------CommDataScript----------------

insert into MAXMESSAGES ( MSGKEY, MSGGROUP, VALUE, TITLE, DISPLAYMETHOD, OPTIONS, BUTTONTEXT, MAXMESSAGESID, MSGID, EXPLANATION, ADMINRESPONSE, OPERATORRESPONSE, SYSTEMACTION, PREFIX) values ( 'autoseturl', 'mobileversion', '是否设置URL?', null, 'MSGBOX', 24, null, MAXMESSAGESSEQ.nextval, 'BMXAA9121I', null, null, null, null, 1);


----------------Update Maximo Sequence----------------

update maxsequence set maxreserved=(select max(MAXMESSAGESID)+1 from MAXMESSAGES) where tbname='MAXMESSAGES' and name='MAXMESSAGESID';



---系统属性---{{{1
PROPNAME:snow.mobilevers.doclink.url
DESCRIPTION:doclink前缀url,用于"移动端版本维护"
DISPPROPVALUE:http://xnymaximo.dunanchina.net:9080/doclinks/
